services:
  backend:
    build: ./backend
    container_name: ssa-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./ssa-dashboard
    container_name: ssa-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
